# Generated by Django 2.0.1 on 2018-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyWater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpost',
            name='music',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
