# Generated by Django 2.0.1 on 2018-07-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyWater', '0004_auto_20180723_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.FileField(null=True, upload_to='isemusic'),
        ),
    ]
