# Generated by Django 2.0.1 on 2018-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyWater', '0005_auto_20180723_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.FileField(null=True, upload_to='icymusic'),
        ),
    ]
